"""Add cascade delete to messages

Revision ID: 5eef67b88b68
Revises: f931b4b72783
Create Date: 2025-03-18 19:31:34.758579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eef67b88b68'
down_revision: Union[str, None] = 'f931b4b72783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
