"""add stars field

Revision ID: e309ab8804a8
Revises: 15f746fdc78e
Create Date: 2025-03-27 06:55:31.921124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e309ab8804a8'
down_revision: Union[str, None] = '15f746fdc78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'comment')
    op.drop_column('messages', 'stars')
    # ### end Alembic commands ###
